# Generated by Django 5.2.7 on 2025-11-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age_text', models.CharField(blank=True, help_text="Human-friendly age text, e.g. '1-2 years'", max_length=100)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dogs/')),
                ('apply_url', models.URLField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering integer; lower shows first')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
